-- DEPRECATED (Phase C)
-- =============================================================================
-- Do not use this file as the schema / RLS path.
--
-- Schema, metadata column, indexes, type CHECK, FKs, and RLS:
--   migrations/20260910_phase_c_supabase_baseline.sql
--
-- How to apply:
--   migrations/README.md
--
-- Storage bucket + storage.objects policies (Phase D, not Phase C):
--   SUPABASE_STORAGE_SETUP.md
-- =============================================================================

-- Intentionally empty. Historical copies mixed FK fixes, storage, and
-- `ALTER TABLE links ADD COLUMN metadata`. Those live in the files above.
